interfaces = []
exclude = ["migrations"]
source_roots = [
    ".",
]
root_module = "allow"

# Dependency Injection module - orchestrates all modules
[[modules]]
path = "di"
depends_on = ["api", "modules.content_generation", "modules.notifications", "modules.marketplace_integration", "modules.product_management", "modules.user_management", "infrastructure"]

# Infrastructure layer - shared utilities only
[[modules]]
path = "infrastructure"
depends_on = []

# Root application - only depends on DI container (clean orchestrator)
[[modules]]
path = "<root>"
depends_on = ["di"]

# Global API layer - can depend on infrastructure for configuration
[[modules]]
path = "api"
depends_on = ["infrastructure", "modules.user_management"]


# User Management module - TRUE INDEPENDENCE with protocols
[[modules]]
path = "modules.user_management"
depends_on = ["infrastructure"]

# Product Management module - TRUE INDEPENDENCE
[[modules]]
path = "modules.product_management"
depends_on = []

# Content Generation module - TRUE INDEPENDENCE
[[modules]]
path = "modules.content_generation"
depends_on = []

# Marketplace Integration module - TRUE INDEPENDENCE
[[modules]]
path = "modules.marketplace_integration"
depends_on = []

# Notifications module - TRUE INDEPENDENCE
[[modules]]
path = "modules.notifications"
depends_on = []
