interfaces = []
exclude = ["migrations"]
source_roots = [
    ".",
]
root_module = "allow"

# Infrastructure layer - shared utilities only
[[modules]]
path = "infrastructure"
depends_on = []

# Root application - only depends on api and infrastructure (clean orchestrator)
[[modules]]
path = "<root>"
depends_on = ["api", "infrastructure"]

# Global API layer - can depend on infrastructure and modules for creating dependencies
[[modules]]
path = "api"
depends_on = ["infrastructure", "modules.user_management"]


# User Management module - TRUE INDEPENDENCE with protocols
[[modules]]
path = "modules.user_management"
depends_on = []

# Product Management module - TRUE INDEPENDENCE
[[modules]]
path = "modules.product_management"
depends_on = []

# Content Generation module - TRUE INDEPENDENCE
[[modules]]
path = "modules.content_generation"
depends_on = []

# Marketplace Integration module - TRUE INDEPENDENCE
[[modules]]
path = "modules.marketplace_integration"
depends_on = []

# Notifications module - TRUE INDEPENDENCE
[[modules]]
path = "modules.notifications"
depends_on = []
