interfaces = []
exclude = []
source_roots = [
    ".",
]
root_module = "allow"

# Dependency Injection module - orchestrates all modules
[[modules]]
path = "di"
depends_on = ["modules.content_generation", "modules.notifications", "modules.marketplace_integration", "modules.product_management", "modules.user_management", "infrastructure"]

# Infrastructure layer - shared utilities only
[[modules]]
path = "infrastructure"
depends_on = []

# Root application - needs API and infrastructure (main.py proves it)
[[modules]]
path = "<root>"
depends_on = ["api", "infrastructure"]

# Global API layer - clean
[[modules]]
path = "api"
depends_on = []


# User Management module - TRUE INDEPENDENCE with protocols
[[modules]]
path = "modules.user_management"
depends_on = []

# Product Management module - TRUE INDEPENDENCE
[[modules]]
path = "modules.product_management"
depends_on = []

# Content Generation module - TRUE INDEPENDENCE
[[modules]]
path = "modules.content_generation"
depends_on = []

# Marketplace Integration module - TRUE INDEPENDENCE
[[modules]]
path = "modules.marketplace_integration"
depends_on = []

# Notifications module - TRUE INDEPENDENCE
[[modules]]
path = "modules.notifications"
depends_on = []
