interfaces = []
exclude = ["domain/entities", "domain/services"]
source_roots = [
    ".",
]
root_module = "allow"

[[modules]]
path = "<root>"
depends_on = []

[[modules]]
path = "modules.user"
depends_on = []

[[modules]]
path = "modules.product"
depends_on = []

[[modules]]
path = "modules.communications"
depends_on = []

[[modules]]
path = "modules.ai_content"
depends_on = ["modules.product"]

[[modules]]
path = "modules.mercadolibre"
depends_on = ["modules.product"]

[[modules]]
path = "modules.auth"
depends_on = ["modules.user"]
