interfaces = []
exclude = []
source_roots = [
    ".",
]

[[modules]]
path = "<root>"
depends_on = [
    "api",
    "infrastructure",
]

[[modules]]
path = "api"
depends_on = []

[[modules]]
path = "application"
depends_on = []

[[modules]]
path = "domain"
depends_on = []

[[modules]]
path = "infrastructure"
depends_on = []
