interfaces = []
exclude = []
source_roots = [
    ".",
]

[[modules]]
path = "<root>"
depends_on = []

[[modules]]
path = "modules.ai_content"
depends_on = [
    "<root>",
    "modules.product",
]

[[modules]]
path = "modules.auth"
depends_on = [
    "modules.user",
]

[[modules]]
path = "modules.communications"
depends_on = []

[[modules]]
path = "modules.mercadolibre"
depends_on = [
    "<root>",
]

[[modules]]
path = "modules.product"
depends_on = [
    "<root>",
]

[[modules]]
path = "modules.user"
depends_on = [
    "<root>",
]
