interfaces = []
exclude = []
source_roots = [
    ".",
]
root_module = "allow"

# Infrastructure layer - shared infrastructure, can depend on modules for protocols
[[modules]]
path = "infrastructure"
depends_on = ["<root>", "modules.ai_content", "modules.communications", "modules.mercadolibre", "modules.product", "modules.user", "modules.user_management"]

# Root application - global orchestration
[[modules]]
path = "<root>"
depends_on = ["infrastructure", "api"]

# Global API layer
[[modules]]
path = "api"
depends_on = []

# Global application orchestration
[[modules]]
path = "application"
depends_on = []

# User Management module (unified user + auth) - can use infrastructure
[[modules]]
path = "modules.user_management"
depends_on = ["infrastructure"]

# Legacy Auth module - can use infrastructure
[[modules]]
path = "modules.auth"
depends_on = ["infrastructure"]

# Legacy User module - can use infrastructure
[[modules]]
path = "modules.user"
depends_on = ["infrastructure"]

# Product module - can use infrastructure
[[modules]]
path = "modules.product"
depends_on = ["infrastructure"]

# AI Content module - can use infrastructure
[[modules]]
path = "modules.ai_content"
depends_on = ["infrastructure"]

# MercadoLibre Integration module - can use infrastructure
[[modules]]
path = "modules.mercadolibre"
depends_on = ["infrastructure"]

# Communications module - can use infrastructure
[[modules]]
path = "modules.communications"
depends_on = ["infrastructure"]
