interfaces = []
exclude = []
source_roots = [
    ".",
]
root_module = "allow"

# Infrastructure layer - shared infrastructure only
[[modules]]
path = "infrastructure"
depends_on = ["<root>"]

# Root application - global orchestration
[[modules]]
path = "<root>"
depends_on = ["infrastructure", "api"]

# Global API layer
[[modules]]
path = "api"
depends_on = []

# Global application orchestration
[[modules]]
path = "application"
depends_on = []

# User Management module (unified user + auth) - completely independent
[[modules]]
path = "modules.user_management"
depends_on = []
