interfaces = []
exclude = []
source_roots = [
    ".",
]
root_module = "allow"

[[modules]]
path = "<root>"
depends_on = [
    "infrastructure",
    "modules.auth.api",
    "modules.product.domain",
    "modules.user.domain",
    "modules.user.infrastructure",
]

[[modules]]
path = "infrastructure"
depends_on = [
    "modules.ai_content.domain",
    "modules.communications.domain",
    "modules.mercadolibre.domain",
    "modules.product.domain",
    "modules.user.domain",
]

[[modules]]
path = "modules.ai_content.api"
depends_on = []

[[modules]]
path = "modules.ai_content.application"
depends_on = []

[[modules]]
path = "modules.ai_content.domain"
depends_on = []

[[modules]]
path = "modules.ai_content.infrastructure"
depends_on = [
    "infrastructure",
]

[[modules]]
path = "modules.auth.api"
depends_on = [
    "infrastructure",
    "modules.auth.application",
    "modules.auth.domain",
    "modules.auth.infrastructure",
    "modules.user.domain",
    "modules.user.infrastructure",
]

[[modules]]
path = "modules.auth.application"
depends_on = [
    "modules.auth.domain",
    "modules.auth.infrastructure",
    "modules.user.domain",
]

[[modules]]
path = "modules.auth.domain"
depends_on = [
    "modules.user.domain",
]

[[modules]]
path = "modules.auth.infrastructure"
depends_on = [
    "infrastructure",
    "modules.auth.api",
    "modules.auth.domain",
]

[[modules]]
path = "modules.communications.api"
depends_on = []

[[modules]]
path = "modules.communications.application"
depends_on = []

[[modules]]
path = "modules.communications.domain"
depends_on = []

[[modules]]
path = "modules.communications.infrastructure"
depends_on = []

[[modules]]
path = "modules.mercadolibre.api"
depends_on = []

[[modules]]
path = "modules.mercadolibre.application"
depends_on = []

[[modules]]
path = "modules.mercadolibre.domain"
depends_on = []

[[modules]]
path = "modules.mercadolibre.infrastructure"
depends_on = [
    "infrastructure",
]

[[modules]]
path = "modules.product.api"
depends_on = []

[[modules]]
path = "modules.product.application"
depends_on = []

[[modules]]
path = "modules.product.domain"
depends_on = []

[[modules]]
path = "modules.product.infrastructure"
depends_on = [
    "infrastructure",
]

[[modules]]
path = "modules.user.api"
depends_on = []

[[modules]]
path = "modules.user.application"
depends_on = []

[[modules]]
path = "modules.user.domain"
depends_on = []

[[modules]]
path = "modules.user.infrastructure"
depends_on = [
    "infrastructure",
    "modules.user.domain",
]
